/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "light-grey": "#EFF0F1",
        grey: "#919698",
        "dark-grey": "#3C3C4399",
        dark: "#1F2029",
        app: "#F9F9F9",
        water: "#4592C3",
        waterDark: "#43a2de",
        waterLight: "#00d4ff",
        ghost: "#7B62A3",
        ghostDark: "#9477c2",
        ghostLight: "#d87df1",
        poison: "#BA7EC8",
        poisonDark: "#b55fc9",
        poisonLight: "#fc7cc8",
        grass: "#95C24D",
        grassDark: "#7ECD8B",
        grassLight: "#89E2B3",
        normal: "#A3ACAE",
        normalDark: "#b5bfc2",
        normalLight: "#dcf9ff",
        fire: "#FD7D25",
        fireDark: "#E58061",
        fireLight: "#DBB469",
        flying: "#A890F0",
        flyingDark: "#826ac9",
        flyingLight: "#dab0e9",
        bug: "#A8B820",
        bugDark: "#92c21e",
        bugLight: "#8fff76",
        electric: "#F8D030",
        electricDark: "#dfbf39",
        electricLight: "#faff80",
        ground: "#E0C068",
        groundDark: "#e0b068",
        groundLight: "#fffb6b",
        fairy: "#EE99AC",
        fairyDark: "#ed859c",
        fairyLight: "#ffdbdb",
        fighting: "#C03028",
        fightingDark: "#ec4137",
        fightingLight: "#ff865e",
        psychic: "#F85888",
        psychicDark: "#f858ac",
        psychicLight: "#ffa1e2",
        steel: "#B8B8D0",
        steelDark: "#a7a7eb",
        steelLight: "#f0eefa",
        ice: "#98D8D8",
        iceDark: "#52d2d2",
        iceLight: "#b6f4ff",
        dragon: "#7038F8",
        dragonDark: "#9c38f8",
        dragonLight: "#647eff",
        rock: "#B8A038",
        rockDark: "#d1a726",
        rockLight: "#fff384",
      },
      fontFamily: {
        display: ["SF Pro Display"],
        text: ["SF Pro Text"],
      },
      fontSize: {
        large: "17px",
        normal: "15px",
      },
      gridTemplateColumns: {
        responsive: "repeat(auto-fit, minmax(250px, 1fr))",
        // cards: "repeat(auto-fit, minmax(250px, 1fr))",
        // cardsLg: "repeat(auto-fit, minmax(335px, 1fr))",
      },
      boxShadow: {
        card: "0px 15px 15px rgba(0, 0, 0, 0.04)",
      },
      keyframes: {
        slowSpin: {
          "0%": { transform: "rotate(0deg)" },
          "70%,100%": { transform: "rotate(720deg)" },
        },
      },
      animation: {
        "spin-slow": "slowSpin 1.5s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
